In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from pandas_profiling import ProfileReport

pd.set_option('display.max_columns', None)

In [2]:
def read_all_files(raw=False, sample=False, filetype='parquet', hexagons=False, resolution='hex_res_7'):
    if filetype=='parquet':
        if hexagons:
                data_dir = Path("../../data/input/hexagons/"+resolution+"/")
                trip_data_df = pd.concat(
                    pd.read_parquet(parquet_file)
                    for parquet_file in data_dir.glob('*.parquet'))
                trip_data_df.reset_index(inplace=True, drop=True)
                return trip_data_df
        elif sample:
            data_dir = Path("../../data/input/trip_data_sample.parquet")
            trip_data = pd.read_parquet(data_dir)
            return trip_data
        else:
            if raw:
                data_dir = Path("../../data/input/raw/")
                trip_data_df = pd.concat(
                    pd.read_parquet(parquet_file)
                    for parquet_file in data_dir.glob('*.parquet'))
                trip_data_df.reset_index(inplace=True, drop=True)
                return trip_data_df
            if not raw:
                data_dir = Path("../../data/input/clean/")
                trip_data_df = pd.concat(
                    pd.read_parquet(parquet_file)
                    for parquet_file in data_dir.glob('*.parquet'))
                trip_data_df.reset_index(inplace=True, drop=True)
                return trip_data_df
    elif filetype=='geojson':
        data_dir = Path("../../data/input/Boundaries_Census_Tracts.geojson")
        geojson = gpd.read_file(data_dir)
        return geojson

In [3]:
trip_data = read_all_files()
trip_data

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,tips,tolls,extras,trip_total,payment_type,pickup_census_tract,pickup_community_area,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,dropoff_census_tract,company
0,9fcf60778776d18664b86e1d90b8b7e17bfb5ec4,21ec4ac0cf9503bdc658259e6bef00bf7bdfed29cf1c79...,2013-01-01 00:15:00,2013-01-01 00:15:00,60.0,0.1,3.45,0.0,0.0,1.0,4.45,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,Dispatch Taxi Affiliation
1,2fe449216fde28acf8c903d5a6c4f73a3df3487e,4b962aba86f28aa453dedfd53d6e98cf4aba8551184dda...,2013-01-01 00:15:00,2013-01-01 00:30:00,1620.0,5.0,15.85,0.0,0.0,2.0,17.85,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
2,934ee1127ca02c948e10ce6944a95c804e630e81,7155fb4a27bc60e860cf4976b48594989f11b69f4c3e2e...,2013-01-01 00:15:00,2013-01-01 00:30:00,600.0,0.9,6.65,0.0,0.0,2.5,9.15,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
3,5956895501996b12683bc2c590e0e4a888f01285,5422457a4d9232e2885ccd05f2f0a29581ebe0d22bf5b4...,2013-01-01 00:15:00,2013-01-01 00:15:00,660.0,4.8,12.85,0.0,0.0,0.0,12.85,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
4,ebf608bb234a9998ae53df2c0b24d485b2e8b800,3193614caa6721a4dbad29c3c7ef58ab2784e87e2db41f...,2013-01-01 00:15:00,2013-01-01 00:15:00,240.0,1.2,5.45,0.0,0.0,1.0,6.45,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15050297,a155865e7578ddd52ed77443c6fed7f981c694b1,cc33cdc1816a9ba9822dd033062f8d414cac183bbfa7fc...,2013-12-31 23:45:00,2013-12-31 23:45:00,536.0,1.6,6.85,3.0,NaN,0.0,9.85,Credit Card,1.703106e+10,6.0,41.941556,-87.666289,"{'coordinates': [-87.6662888874, 41.941555829]...",3.0,41.965446,-87.663196,"{'coordinates': [-87.6631958495, 41.9654457842...",1.703103e+10,American United
15050298,35a5fe3a96ad453a9276112136c934a87379e8a5,341cead8979074196f3231099ef811c4e905d7031dd6d7...,2013-12-31 23:45:00,2014-01-01 00:15:00,1952.0,8.5,21.45,0.0,NaN,2.0,23.45,Cash,NaN,28.0,41.874005,-87.663518,"{'coordinates': [-87.6635175498, 41.874005383]...",6.0,41.944227,-87.655998,"{'coordinates': [-87.6559981815, 41.9442266014...",NaN,American United
15050299,f6fa0574a62cab2fec2c9ea2cc075f8ff6ee19e5,c01573d08b208b89c0fdf054d7bc2820fe2abb9d326a80...,2013-12-31 23:45:00,2013-12-31 23:45:00,262.0,0.9,5.25,0.0,NaN,2.0,7.25,Cash,1.703132e+10,32.0,41.884987,-87.620993,"{'coordinates': [-87.6209929134, 41.8849871918...",8.0,41.898332,-87.620763,"{'coordinates': [-87.6207628651, 41.8983317935...",1.703108e+10,American United
15050300,de95a68aae83de22d19a7999111f249e90eae812,5866e731fed5c82556c87a73b3ec2e19dd13d4cdc46a34...,2013-12-31 23:45:00,2013-12-31 23:45:00,352.0,0.7,5.05,2.0,NaN,0.0,7.05,Credit Card,1.703106e+10,6.0,41.942577,-87.647079,"{'coordinates': [-87.6470785093, 41.942577185]...",6.0,41.934540,-87.643023,"{'coordinates': [-87.6430228044, 41.9345397158...",1.703106e+10,American United
15050301,2520e0373a96d517bfdebf51df22d1cefa0ac2c3,c7475fec1fa338d525948b60cc20c8a47905a257c68ef8...,2013-12-31 23:45:00,2014-01-01 00:00:00,1141.0,4.4,13.05,0.0,NaN,1.5,14.55,Cash,1.703132e+10,32.0,41.884987,-87.620993,"{'coordinates': [-87.6209929134, 41.8849871918...",24.0,41.912364,-87.675063,"{'coordinates': [-87.6750627566, 41.9123643542...",1.703124e+10,American United

In [5]:
trip_data_sample = read_all_files(sample=True)
trip_data_sample

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,tips,tolls,extras,trip_total,payment_type,pickup_census_tract,pickup_community_area,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,dropoff_census_tract,company
17571298,13e52cdcd0bdde762e0ef74b9cd17d9f65f8a680,020531ad67ef679261206ce9876298202b29824371fcf9...,2013-09-07 15:45:00,2013-09-07 15:45:00,240.0,0.00,4.65,0.00,0.0,1.0,5.65,Cash,1.703108e+10,8.0,41.898332,-87.620763,"{'coordinates': [-87.6207628651, 41.8983317935...",8.0,41.899156,-87.626211,"{'coordinates': [-87.6262105324, 41.8991556134...",1.703108e+10,Taxi Affiliation Services
17825359,d260876b864c375c3da70a848c3bf4cd305c58ac,288345b3a0280dabfb23a38ba7fc482e59bb37c2109b0a...,2013-09-10 20:30:00,2013-09-10 20:45:00,1620.0,0.00,15.05,3.40,0.0,2.0,20.45,Credit Card,1.703108e+10,8.0,41.891972,-87.612945,"{'coordinates': [-87.6129454143, 41.8919715078...",8.0,41.902788,-87.626146,"{'coordinates': [-87.6261455896, 41.9027880476...",1.703108e+10,Northwest Management LLC
11638745,ebcbfcbb162159ca0b130d1e5388784a088d52ab,24fe18cb099f758873795f1ac94b0eccc74f65efab09f5...,2013-06-21 15:00:00,2013-06-21 15:45:00,3060.0,0.00,35.65,7.73,0.0,3.0,46.38,Credit Card,NaN,2.0,42.001571,-87.695013,"{'coordinates': [-87.6950125892, 42.001571027]...",76.0,41.980264,-87.913625,"{'coordinates': [-87.913624596, 41.9802643146]...",NaN,Taxi Affiliation Services
16232104,8f5bb3426366e9568a788309ede90ddf4890eb25,8ef636eba91edd8357005da763e71251229230bbf9f6b4...,2013-08-20 13:30:00,2013-08-20 13:45:00,1117.0,10.70,23.45,0.00,NaN,1.0,24.45,Cash,1.703128e+10,28.0,41.879255,-87.642649,"{'coordinates': [-87.642648998, 41.8792550844]...",56.0,41.785999,-87.750934,"{'coordinates': [-87.7509342894, 41.785998518]...",1.703198e+10,Flash Cab
23376171,7cd3171f7061099813e30e8bde90000f2bdb641c,b46c23f64dabd4ec878a64e95739d0903d53afd8d992e3...,2013-11-16 01:30:00,2013-11-16 01:45:00,420.0,0.00,7.25,0.00,0.0,0.0,7.25,Cash,1.703128e+10,28.0,41.885300,-87.642808,"{'coordinates': [-87.6428084655, 41.8853000224...",8.0,41.900266,-87.632109,"{'coordinates': [-87.6321092196, 41.9002656868...",1.703108e+10,Taxi Affiliation Services
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7591971,98c26dcc8ccd2606ceef5a03d37d043e051d0476,ab44501ecc8f9ff89c3550d26b04014a7f70640b0691cf...,2013-04-28 00:15:00,2013-04-28 00:00:00,NaN,0.00,15.85,2.00,0.0,0.0,17.85,Credit Card,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,Taxi Affiliation Services
11831037,36c1e3ab5bf8eaec1c3154fac1ac4c942a43ecf6,12459cd7e30dbaeb112b2c7d038e650d7417044e7909df...,2013-06-23 15:15:00,2013-06-23 15:30:00,840.0,0.10,10.65,0.00,0.0,1.0,11.65,Cash,1.703107e+10,7.0,41.914616,-87.631717,"{'coordinates': [-87.6317173661, 41.9146162864...",28.0,41.879255,-87.642649,"{'coordinates': [-87.642648998, 41.8792550844]...",1.703128e+10,Taxi Affiliation Services
18499939,ba7013203fb5984756c94d030a41e44663e3840d,4eb40b896dad29b18e1f9577205d3786392ac6fd1e312f...,2013-09-19 09:30:00,2013-09-19 09:45:00,420.0,0.11,5.85,0.00,0.0,1.5,7.35,Cash,1.703132e+10,32.0,41.884987,-87.620993,"{'coordinates': [-87.6209929134, 41.8849871918...",8.0,41.892042,-87.631864,"{'coordinates': [-87.6318639497, 41.8920421365...",1.703108e+10,None
22949198,5c9ec69fd18ece2f5f5f26fc0fddd0d3c03633e6,3f73616a6d4508a03d5bcdee0a14daa7a920f291747544...,2013-11-11 06:30:00,2013-11-11 06:45:00,1140.0,9.70,24.05,3.61,0.0,0.0,27.66,Credit Card,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
21179378,8958721ef76f57c59982ae2853765a2c76bf39d4,7a9c5c79f3e8300b7b106c5c5134357517a128617fb94f...,2013-10-21 16:45:00,2013-10-21 16:45:00,240.0,0.70,4.84,0.00,0.0,0.0,4.84,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None

In [4]:
# function to clean and save dataset
def cleaning_loop(trip_data, save=True, sample_set=False, frac=0.3):
    print('Let the cleaning begin ...')
    trip_data.drop_duplicates("trip_id", inplace=True)
    print('dropped duplicates')
    
    
    numeric_cols = ["trip_seconds", "trip_miles", "fare", "tips", 
                "tolls", "extras", "trip_total", "pickup_census_tract",
                "pickup_community_area", "pickup_centroid_latitude",
                "pickup_centroid_longitude", "dropoff_community_area",
                "dropoff_centroid_latitude", "dropoff_centroid_longitude",
                "dropoff_census_tract"]
    string_cols = ["trip_id", "taxi_id", "payment_type", "company"]
    datetime_cols = ["trip_start_timestamp", "trip_end_timestamp"]
    #geo_cols = ["pickup_centroid_location", "dropoff_centroid_location"]
    
    trip_data[numeric_cols] = trip_data[numeric_cols].apply(pd.to_numeric)
    print('Changed numeric types')
    trip_data[datetime_cols] = trip_data[datetime_cols].apply(pd.to_datetime)
    print('Changed datetime types')
    trip_data[string_cols] = trip_data[string_cols].astype(str)
    print('Changed string types')
    
    
    # DATA CLEANING SHOULD BE MADE HERE
    trip_data = trip_data[trip_data['trip_start_timestamp'] > '2013-01-01 00:00:00']
    trip_data = trip_data[trip_data['trip_start_timestamp'] < '2013-12-31 23:59:59']
    trip_data = trip_data[trip_data['trip_end_timestamp'] > '2013-01-01 00:00:00']
    trip_data = trip_data[trip_data['trip_start_timestamp'] < '2014-01-01 23:59:59']
    print('cutted years')
    
    trip_data = trip_data[trip_data['fare'].between(1, 7000)]
    trip_data = trip_data[trip_data['trip_miles'].between(0.01, 7000)]
    trip_data = trip_data[trip_data['trip_seconds'].between(20, 7000)]
    trip_data = trip_data[trip_data['trip_total'].between(1, 7000)]
    print('filtered extreme values')
    
    
    if save:
        if sample_set:
            trip_data_sample = trip_data.sample(frac=frac)
            trip_data_sample.to_parquet(Path("../../data/input/trip_data_sample.parquet"))
            print('Sample set created')
            return trip_data_sample
        else:
            print('Saving/Overwriting in progress ...')
            trip_data1 = trip_data[:int(len(trip_data)*0.25)]
            print('First split')
            trip_data2 = trip_data[int(len(trip_data)*0.25):int(len(trip_data)*0.5)]
            print('Second split')
            trip_data3 = trip_data[int(len(trip_data)*0.5):int(len(trip_data)*0.75)]
            print('Third split')
            trip_data4 = trip_data[int(len(trip_data)*0.75):]
            print('Forth split')

            trip_data1.to_parquet(Path("../../data/input/clean/trip_data1.parquet"))
            print('Saved No. 1')

            trip_data2.to_parquet(Path("../../data/input/clean/trip_data2.parquet"))
            print('Saved No. 2')

            trip_data3.to_parquet(Path("../../data/input/clean/trip_data3.parquet"))
            print('Saved No. 3')

            trip_data4.to_parquet(Path("../../data/input/clean/trip_data4.parquet"))
            print('Saved No. 4')

    return trip_data

In [17]:
# run cleaning loop
trip_data_clean = cleaning_loop(trip_data)
trip_data_clean

Let the cleaning begin ...
dropped duplicates
cutted years
filtered extreme values
Changed numeric types
Changed datetime types
Changed string types
Saving/Overwriting in progress ...
First split
Second split
Third split
Forth split
Saved No. 1
Saved No. 2
Saved No. 3
Saved No. 4

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,tips,tolls,extras,trip_total,payment_type,pickup_census_tract,pickup_community_area,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,dropoff_census_tract,company
0,eda829a425ca1da13e1130c700c876881e26ff9a,b47c583b142d75b42882975eaab19c6cb98d8268601657...,2013-01-01,2013-01-01 00:15:00,600.0,3.0,9.65,0.00,0.0,0.0,9.65,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
1,0c2b3705c9748a5949bf5b7d727b2d1f2e18805f,c2280976049b22e58ce53a17263114616be76981b9ac56...,2013-01-01,2013-01-01 00:30:00,1320.0,12.3,26.25,0.00,0.0,0.0,26.25,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
2,c15dc571c96c36e44bc4ed50f40330e9f0a21650,294ae9e2f433bb460731f9199b1837de3cf88ad987a42b...,2013-01-01,2013-01-01 00:30:00,1320.0,6.3,16.45,1.00,0.0,2.0,19.45,Credit Card,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
3,3c979de8d901f317228a40673c3923d72104b92c,2db2ec3555e44930a5d41596cb7935af41c30c30381672...,2013-01-01,2013-01-01 01:30:00,5520.0,88.8,164.25,63.56,0.0,90.0,317.81,Credit Card,1.703106e+10,6.0,41.942585,-87.656644,"{'coordinates': [-87.6566440918, 41.9425851797...",NaN,NaN,NaN,None,NaN,None
4,27ad87f629bf14fa3cb894daad514cdad4736f9c,4b38941e0745acdeefe630832a438a59fdaac78640f68a...,2013-01-01,2013-01-01 00:15:00,900.0,2.7,10.45,0.00,0.0,1.0,11.45,Cash,NaN,28.0,41.874005,-87.663518,"{'coordinates': [-87.6635175498, 41.874005383]...",8.0,41.899602,-87.633308,"{'coordinates': [-87.6333080367, 41.899602111]...",NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27219094,3933014e3e1f3667a010af77f212dee42b89800d,c6adb6baeda007c313bcfac69d067e70ee395117472210...,2014-01-01,2014-01-01 00:00:00,0.0,0.0,20.45,0.00,0.0,0.0,20.45,No Charge,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,Taxi Affiliation Services
27219095,c8b1c41f6b6e60396bb2bd897c2204fc4ab5f3f4,74b5fd40ec7eaff971444da67e7ad41d22c0b518901368...,2014-01-01,2014-01-01 00:00:00,60.0,0.0,8.65,3.00,0.0,0.0,11.65,Credit Card,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,Taxi Affiliation Services
27219096,ef7dcaf56d0bd591719df6b7b463771c8684fdca,41bbe7567ceabf10d1eb4bb12ef33421a94ca4bb2dfbd4...,2014-01-01,2014-01-01 00:15:00,720.0,0.0,7.85,1.57,0.0,0.0,9.42,No Charge,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,Chicago Elite Cab Corp. (Chicago Carriag
27219097,871b1b35cdb30a11f2b959dbb3f26fbdab3f1dd7,eecaba329d22b57acd34be5c5604891308b1c4d0f95f06...,2014-01-01,2013-12-31 23:45:00,NaN,0.0,15.25,2.29,0.0,0.0,17.54,Credit Card,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,Chicago Elite Cab Corp. (Chicago Carriag
27219098,1def06cd47e2884c7552f630fc0f12af0f718232,eab5b3c1b36c34fd68a587df811846acd2d67eb019196b...,2014-01-01,2014-01-01 00:15:00,960.0,3.9,11.85,0.00,0.0,0.0,11.85,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,Chicago Medallion Management

In [5]:
trip_data_sample = cleaning_loop(trip_data, sample_set=True)
trip_data_sample

Let the cleaning begin ...
dropped duplicates
Changed numeric types
Changed datetime types
Changed string types
cutted years
filtered extreme values
Sample set created

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,tips,tolls,extras,trip_total,payment_type,pickup_census_tract,pickup_community_area,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,dropoff_census_tract,company
15682557,ecb7736258ccc9885843ab4812403c02d287ea5a,e5c165fcc578673a02367d8d379846b48b00fbacf7f1b4...,2013-08-13 10:30:00,2013-08-13 10:30:00,360.0,1.3,6.45,0.00,0.0,0.0,6.45,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
12211112,95e0d77a57c76e5a885a03a29c61396115229749,2f5a8b67f988625ed892f9f87d48255861bae9beaeb573...,2013-06-28 18:15:00,2013-06-28 18:30:00,600.0,1.2,6.85,0.00,0.0,1.0,7.85,Cash,1.703108e+10,8.0,41.898332,-87.620763,"{'coordinates': [-87.6207628651, 41.8983317935...",8.0,41.892042,-87.631864,"{'coordinates': [-87.6318639497, 41.8920421365...",1.703108e+10,None
2361088,12033fd51c7710c80265e2df044655bd6fb1bd24,36c49e0df2325e7e57fc13127f76b6962b2697184dab38...,2013-02-14 00:45:00,2013-02-14 01:00:00,780.0,1.5,15.85,0.00,0.0,0.0,15.85,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
2479418,e513f8f342774d9f5f64c080bef0af84ff091049,2f1df8a630d47fa448585b72a26287f920aa3349fb90e6...,2013-02-15 20:00:00,2013-02-15 20:30:00,1140.0,0.1,11.25,0.00,0.0,1.0,12.25,Cash,1.703108e+10,8.0,41.892073,-87.628874,"{'coordinates': [-87.6288741572, 41.8920726347...",28.0,41.878667,-87.671654,"{'coordinates': [-87.6716536214, 41.8786674201...",1.703184e+10,Taxi Affiliation Services
7723418,fad03f3d5b792c0896b60934a3aaf7a9cffa8bf5,4956d3181718741f82386d54c22d3288ebaba0cfff19c6...,2013-04-30 10:00:00,2013-04-30 10:15:00,660.0,0.1,9.45,0.00,0.0,0.0,9.45,Cash,NaN,6.0,41.944227,-87.655998,"{'coordinates': [-87.6559981815, 41.9442266014...",4.0,41.975171,-87.687516,"{'coordinates': [-87.68751551520002, 41.975170...",NaN,Taxi Affiliation Services
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13979084,013b1cb5cfab75177de7ac4f39c3a8a23073cca3,2e9bb6bc95512aed0405c8f63b7712de3526a75eb144ca...,2013-07-21 18:45:00,2013-07-21 19:00:00,600.0,1.9,8.05,0.00,0.0,1.0,9.05,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
26090563,0aca0c9dbb6da97c6e855f9cab731f26eeadf553,de22250c7bf3b590388f1bd1c2f7ca36c525efbe4438bf...,2013-12-16 21:00:00,2013-12-16 21:00:00,625.0,4.2,11.45,3.11,NaN,1.0,15.56,Credit Card,1.703108e+10,8.0,41.892508,-87.626215,"{'coordinates': [-87.6262149064, 41.8925077809...",6.0,41.942692,-87.651771,"{'coordinates': [-87.6517705068, 41.9426918444...",1.703106e+10,American United
25348687,c95f9c1b0358938d9c21b5ddf879a424e972562f,b5c33c47b123870895f56c87207368e3891752795531cc...,2013-12-09 10:00:00,2013-12-09 10:15:00,180.0,0.6,4.65,0.00,0.0,0.0,4.65,Cash,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None
6902865,d164c5fe227e869b3328d67ed9b86e97fb366627,5b5fd5f13833d7b8d871d1573fb8ef3c1b39417d1802a5...,2013-04-18 22:30:00,2013-04-18 23:00:00,2040.0,1.4,47.25,0.00,0.0,3.0,50.25,Cash,NaN,76.0,41.980264,-87.913625,"{'coordinates': [-87.913624596, 41.9802643146]...",39.0,41.808916,-87.596183,"{'coordinates': [-87.5961833442, 41.8089162826...",NaN,Taxi Affiliation Services
19543672,5b5033d4f802ceb9b9cdd03f72d3b120bed6c910,46f31762f0a886f0b2a870bbd1ac127185937d5179d5f1...,2013-10-01 21:30:00,2013-10-01 21:45:00,240.0,0.8,5.05,0.00,0.0,0.0,5.05,Cash,1.703132e+10,32.0,41.884987,-87.620993,"{'coordinates': [-87.6209929134, 41.8849871918...",8.0,41.892073,-87.628874,"{'coordinates': [-87.6288741572, 41.8920726347...",1.703108e+10,None

trip_data.info()

In [4]:
trip_data_clean = trip_data.drop(['pickup_centroid_location', 'dropoff_centroid_location', 'trip_id', 'taxi_id'], axis=1)
trip_data_clean

,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,tips,tolls,extras,trip_total,payment_type,pickup_census_tract,pickup_community_area,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_community_area,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_census_tract,company
0,2013-01-01 00:15:00,2013-01-01 00:15:00,60.0,0.1,3.45,0.0,0.0,1.0,4.45,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dispatch Taxi Affiliation
1,2013-01-01 00:15:00,2013-01-01 00:30:00,1620.0,5.0,15.85,0.0,0.0,2.0,17.85,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,2013-01-01 00:15:00,2013-01-01 00:30:00,600.0,0.9,6.65,0.0,0.0,2.5,9.15,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,2013-01-01 00:15:00,2013-01-01 00:15:00,660.0,4.8,12.85,0.0,0.0,0.0,12.85,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,2013-01-01 00:15:00,2013-01-01 00:15:00,240.0,1.2,5.45,0.0,0.0,1.0,6.45,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15050297,2013-12-31 23:45:00,2013-12-31 23:45:00,536.0,1.6,6.85,3.0,NaN,0.0,9.85,Credit Card,1.703106e+10,6.0,41.941556,-87.666289,3.0,41.965446,-87.663196,1.703103e+10,American United
15050298,2013-12-31 23:45:00,2014-01-01 00:15:00,1952.0,8.5,21.45,0.0,NaN,2.0,23.45,Cash,NaN,28.0,41.874005,-87.663518,6.0,41.944227,-87.655998,NaN,American United
15050299,2013-12-31 23:45:00,2013-12-31 23:45:00,262.0,0.9,5.25,0.0,NaN,2.0,7.25,Cash,1.703132e+10,32.0,41.884987,-87.620993,8.0,41.898332,-87.620763,1.703108e+10,American United
15050300,2013-12-31 23:45:00,2013-12-31 23:45:00,352.0,0.7,5.05,2.0,NaN,0.0,7.05,Credit Card,1.703106e+10,6.0,41.942577,-87.647079,6.0,41.934540,-87.643023,1.703106e+10,American United
15050301,2013-12-31 23:45:00,2014-01-01 00:00:00,1141.0,4.4,13.05,0.0,NaN,1.5,14.55,Cash,1.703132e+10,32.0,41.884987,-87.620993,24.0,41.912364,-87.675063,1.703124e+10,American United

In [7]:
trips = trip_data_clean.loc[:,trip_data_clean.columns!='taxi_id'].stack().sort_index(level=1).unique()
trip_data_clean.replace(to_replace=trips,value=list(range(len(trips))),inplace=True)
trip_data_clean

MemoryError: Unable to allocate 15.6 MiB for an array with shape (2, 8165730) and data type bool

In [10]:
trip_data_clean_small = trip_data_clean.sample(frac=0.5)

NameError: name 'trip_data_clean' is not defined

In [5]:
del trip_data

In [7]:
del trip_data_clean

In [6]:
profile = ProfileReport(trip_data_clean, title="AAA trip-data-clean - Pandas Profiling Report")

In [7]:
profile.to_widgets()

Summarize dataset:   0%|          | 0/32 [00:00<?, ?it/s]

C:\Users\Christian\Documents\coding\anaconda3\envs\pds_21\lib\site-packages\scipy\stats\stats.py:4594: RuntimeWarning: overflow encountered in longlong_scalars
  (2 * xtie * ytie) / m + x0 * y0 / (9 * m * (size - 2)))

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valu…

In [8]:
profile.to_file(Path("../../data/output/trip-data-report-clean.html"))

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]